// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibvhnisuupxghjwrmdkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlidmhuaXN1dXB4Z2hqd3JtZGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTYzODYsImV4cCI6MjA2MjY5MjM4Nn0.CptULIs7hu0bHu8LPEauG6f1O29zGzIhM1ivfx7Y3xU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);